version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3
jobs:
  sonarbuild:
    working_directory: ~/tmp
    docker:
      - image: "circleci/python:3.6.4"
    sonarcloud:
      sonar.organization: thunderpycode
      sonar.projectKey: thunderpycode_CircleCi
    steps:
      
      - checkout  
      - sonarcloud/scan
  build:
    working_directory: ~/tmp
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py > /tmp/python-artifact;
      - store_artifacts:
          path: /tmp/python-artifact
          destination: artifact-file

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py 
workflows:
  build_and_test:
    jobs:
      - sonarbuild:
          context: sonarcloud
      - build
      - test:
          requires:
            - build