version: 2.1

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: 
          command: |
            python3 main.py > /tmp/art-1;
            mkdir /tmp/artifacts;
            python3 main.py > //tmp/artifacts/art-2;
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main-test.py
 
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build